#Config for the embeddings
tokenizer: "jhu-clsp/mmBERT-small"
model: "jhu-clsp/mmBERT-small"
max_tokens: 8192
collection_name: "appellation_vector_db"
docs_folder: "setup/data/cdc_inao"
hf_timeout: 300
